### PR TITLE
Feature/fix images injection

### PR DESCRIPTION
**Pull request by bneiluj**
Add PNG images for easy reading

### CODE REVIEW

**Comment by iamdefinitelyahuman** [comment]
Maybe we should migrate `doc/README.md` into the root directory?

**Comment by michwill** [comment]
Ehm... Makes it pretty bad in pdf. And formulas are still not rendered by github if you want to use its preview

**Comment by bneiluj** [comment]
with images injection as PNG directly into the readme without calling PDF images then it's fine and REAME can be placed into root directory.

**Comment by michwill** [comment]
It still reads as pretty shit when having formulas, regardless of the images. I'd just put pdf there

**Comment by michwill** [comment]
Like, this reads way better to me: https://github.com/curvefi/curve-dao-contracts/blob/master/doc/readme.pdf

Maybe can name it more prominently and put in root

**Comment by iamdefinitelyahuman** [comment]
Closing as stale

**Pull request closed without merging**
